// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACfvG1uYsd1oKsP1TaFr-6Xv64YUR_CvU',
    appId: '1:667679331975:web:e026e56d4783c6b3a9ca22',
    messagingSenderId: '667679331975',
    projectId: 'meta-tracking-animals',
    authDomain: 'meta-tracking-animals.firebaseapp.com',
    storageBucket: 'meta-tracking-animals.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-5C4O77uwCFx5nhQ7TWZzkqF8M_-lnzA',
    appId: '1:667679331975:android:22830ae96e52f3fba9ca22',
    messagingSenderId: '667679331975',
    projectId: 'meta-tracking-animals',
    storageBucket: 'meta-tracking-animals.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaLDaBT2MiCvs4TSk2aTYTZwpM54H96fQ',
    appId: '1:667679331975:ios:123f6fe371e98574a9ca22',
    messagingSenderId: '667679331975',
    projectId: 'meta-tracking-animals',
    storageBucket: 'meta-tracking-animals.firebasestorage.app',
    iosBundleId: 'com.example.metaTracking',
  );
}
